apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: static-ip-conf
spec:
  config: '{
    "cniVersion": "0.3.1",
	  "name": "lan",
	  "type": "bridge",
	  "bridge": "br-lan",
	  "ipam": {
	    "type": "static",
      "addresses": [
	      {
		      "address": "172.16.0.1/16"
			  }
		  ]
    }
  }'
---
apiversion: apps/v1
kind: networkattachmentdefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
    "cniversion": "0.3.1",
    "type": "macvlan",
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.1.0/24",
      "rangestart": "192.168.1.4",
        "rangeend": "192.168.1.254",
      "routes": [
        { "dst": "0.0.0.0/0" }
      ],
      "gateway": "192.168.1.1"
    }
  }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: Service
metadata:
  name: samba-ad-dc-dns
spec:
  type: ClusterIP
  clusterIP: 172.168.1.1
  selector:
    app: samba-ad-dc-dns
  ports:
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 53
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
---
apiversion: apps/v1
kind: StatefulSet
metadata:
  name: dc
spec:
  selector:
    matchLabels:
      app: samba-ad-dc-dns
  serviceName: samba-ad-dc-dns
  replicas: 1
  template:
    metadata:
      labels:
        app: samba-ad-dc-dns
      annotations:
        k8s.v1.cni.cncf.io/networks: static-ip-conf
    spec:
      containers:
      - image: affixalex/samba-ad-dc-dns:latest
        imagePullPolicy: Always
        name: samba-ad-dc-dns
        volumemounts:
        - name: samba-var-lib
          mountpath: /var/lib
        - name: samba-var-log
          mountpath: /var/log
        - name: samba-etc
          mountpath: /etc
        env:
        - name: SAMBA_DOMAIN
          value: INTERNAL
        - name: SAMBA_REALM
          value: INTERNAL.RELENTLESS.FARM
        - name: SAMBA_DOMAIN_PASSWORD
          value: Artemisr12@
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
        - containerPort: 389
          name: ldap
        - containerPort: 88
          name: kerberos
        - containerPort: 135
          name: epmap
        - containerPort: 139
          name: netbios-ssn
        - containerPort: 138
          name: netbios-dgm
        - containerPort: 445
          name: microsoft-ds
        - containerPort: 464
          name: kpasswd
        - containerPort: 636
          name: ldaps
        - containerPort: 3268
          name: ldp-glob-catalo
        - containerPort: 3269
          name: ldps-glob-cata
        securityContext:
          privileged: true
        volumeMounts:
        - name: samba-var-lib
          mountPath: /var/lib/samba
        - name: samba-etc
          mountPath: /etc/samba
        - name: samba-var-log
          mountPath: /var/log/samba
      volumes:
      - name: samba-var-log
        hostPath:
          path: /opt/samba/samba-var-log
          type: Directory
      - name: samba-var-lib
        hostPath:
          path: /opt/samba/samba-var-lib
          type: Directory
      - name: samba-etc
        hostPath:
          path: /opt/samba/samba-etc
          type: Directory
---
apiversion: apps/v1
kind: networkattachmentdefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniversion": "0.3.1",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangestart": "192.168.1.1",
        "rangeend": "192.168.1.200",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.1.1"
      }
    }'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 172.16.0.1
        cache 30
        loop
        reload
        loadbalance
    }
    samdom.example.com:53 {
       errors
       cache 30
       proxy . 172.168.1.1
    }
